/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary": "#FF0101",
        "primary-container": "#FF0101",
        "inverse-surface": "#27313f",
        "tertiary-fixed-dim": "#ffb784",
        "secondary-fixed-dim": "#c7c5d1",
        "surface-container-highest": "#d9e3f6",
        "tertiary-fixed": "#ffdcc6",
        "on-secondary-fixed": "#1a1b23",
        "outline-variant": "#ccc3d8",
        "error-container": "#ffdad6",
        "background": "#F0EFEA",
        "on-surface": "#FF0101",
        "surface-container-lowest": "#F0EFEA",
        "surface-bright": "#F0EFEA",
        "primary-fixed": "#eaddff",
        "surface": "#F0EFEA",
        "tertiary": "#7d3d00",
        "surface-container-low": "#eff4ff",
        "error": "#ba1a1a",
        "surface-container-high": "#dee9fc",
        "on-primary-container": "#ede0ff",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-container": "#a15100",
        "on-error-container": "#93000a",
        "on-background": "#FF0101",
        "surface-tint": "#732ee4",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#713700",
        "outline": "#7b7487",
        "on-secondary-container": "#64636d",
        "secondary-container": "#e3e1ed",
        "surface-dim": "#d0dbed",
        "secondary": "#5d5d67",
        "on-secondary-fixed-variant": "#46464f",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#e3e1ed",
        "on-primary-fixed": "#25005a",
        "surface-container": "#e6eeff",
        "surface-variant": "#d9e3f6",
        "on-tertiary-container": "#ffe0cd",
        "inverse-primary": "#d2bbff",
        "on-surface-variant": "#FF0101",
        "on-tertiary-fixed": "#301400"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-md": "16px",
        "container-max": "1120px",
        "section-gap": "64px",
        "stack-lg": "32px",
        "gutter": "24px",
        "stack-sm": "8px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "kaushan": ["Kaushan Script", "cursive"],
        "unna": ["Unna", "serif"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
